import Head from 'next/head'
import Image from 'next/image'



export default function Home() {
  return (
    <>
      <Head>
        <title>Guruvel Assosiates</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
      </Head>
      <div className="page">
        <div className="innerpage">

            <div className="bg"></div>


            <div className="navbar">
              <div className="inner">
                <div className="logo">
                  <Image src="/logo.png" width={200} height={70} alt=""/>
                </div>
                <ul className='nav-links'>
                  <li>Overview</li>
                  <li>Exterior</li>
                  <li>Interior</li>
                  <li>Our Team</li>
                  <li>Contact us</li>
                </ul>
              </div> 
            </div>

            <div className="test">
              <h1>hello</h1>
            </div>

        </div>
        
      </div> 
    </>
  )
}

